server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

imgPrefix:  "http://localhost:8081"
hidden-props-path: /Users/u18456857/IdeaProjects/rpg-app-server-v1/src/main/resources/hidden.properties

vk:
  api-version: 5.103

jwt:
  secret: Satan

spring.profiles.active: @spring.profiles.active@
