spring:
  datasource:
    url: jdbc:h2:file:/var/h2/rpg
    username: sa
    password: password
    driver-class-name: org.h2.Driver

server:
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/www.novemis.ru/keystore.p12
    key-store-password: 939388536
    keyStoreType: PKCS12
    keyAlias: tomcat