spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:file:/var/h2/rpg
#    url: jdbc:h2:mem:rpg
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2