spring:
  datasource:
    #    url: jdbc:h2:mem:rpg
    #    username: sa
    #    password: password
    driver-class-name: org.postgresql.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

security:
  require-ssl: true

server:
  ssl:
    key-store: /etc/letsencrypt/live/www.novemis.ru/keystore.p12
    key-store-password: 939388536
    keyStoreType: PKCS12
    keyAlias: tomcat