spring:
  datasource:
    #    url: jdbc:h2:mem:rpg
    #    username: sa
    #    password: password
    driver-class-name: org.postgresql.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.Postgresql9Dialect
