server:
  port: 8080
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: Qhxmfa49
#    key-alias: tomcat

spring:
  codec:
    max-in-memory-size: 10MB
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/rpg
    username: rpg
    password: rpg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

imgPrefix:  "http://localhost:8081"
hidden-props-path: /home/nikolay/.config/hidden.properties

vk:
  api-version: 5.103

jwt:
  secret: Satan