spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rpg
    username: rpg
    password: rpg
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/www.novemis.ru/keystore.p12
    key-store-password: 939388536
    keyStoreType: PKCS12
    keyAlias: tomcat